run:
  timeout: 2m

linters:
  enable-all: true
  disable:
    - exportloopref # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - dupl
    - prealloc
    - wsl
    - nlreturn
    - stylecheck
    - testpackage
    - paralleltest
    - tparallel
    - wrapcheck
    - exhaustive
    - exhaustruct
    - makezero
    - godot
    - varnamelen
    - nilnil

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 5
    min-occurrences: 3
  mnd:
    ignored-functions:
      - os.*
  misspell:
    locale: US
    ignore-words:
      - hardlinked
      - behaviour
  funlen:
    lines: -1
    statements: 50
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/instana/testify"
            desc: not allowed
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
#    settings:
#      hugeParam:
#        sizeThreshold: 220 # todo must be improved
  forbidigo:
    forbid:
      - ^print(ln)?$
      - ^spew\.Print(f|ln)?$
      - ^spew\.Dump$
  tagliatelle:
    case:
      rules:
        json: snake
  gosec:
    excludes:
      - G204
  perfsprint:
    err-error: true
    errorf: true
    sprintf1: true
    strconcat: false

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'package-comments: should have a package comment'
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - funlen
    - path: branch/branch.go
      text: func name will be used as branch.BranchName by other packages
    - path: push/push_gen.go
      text: func name will be used as push.PushOption by other packages
    - path: notes/notes_custom.go
      text: func name will be used as notes.NotesRef by other packages
    - path: doc.go
      text: don't use an underscore in package name
    - path: internal/generator.go
      text: '`expCmd(.+)` is a global variable'
    - path: internal/generator.go
      text: 'G306:'
    - path: internal/generator.go
      text: 'mnd: Magic number: 0644, in <argument> detected'

output:
  show-stats: true
